### ISSUE TITLE
Demo is out Dated its not working for angular

### ISSUE THREAD

**Issue by MuhammadTahir92** [yezarela/nativescript-image-cache#20]
error log is 
```
System.err: com.tns.NativeScriptException:
System.err: Calling js method getView failed
System.err: TypeError: Could not load view for: ImageCacheIt.Error: com.tns.NativeScriptException: Failed to find module: "nativescript-image-cache-it", relative to: app/tns_modules/
System.err:     com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     com.tns.gen.android.widget.BaseAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.getView(BaseAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.java:47)
System.err:     android.widget.AbsListView.obtainView(AbsListView.java:2346)
System.err:     android.widget.ListView.measureHeightOfChildren(ListView.java:1280)
System.err:     android.widget.ListView.onMeasure(ListView.java:1188)
System.err:     android.view.View.measure(View.java:18788)
System.err:     org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     org.nativescript.widgets.StackLayout.onMeasure(StackLayout.java:83)
System.err:     android.view.View.measure(View.java:18788)
System.err:     org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1055)
System.err:     org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:865)
System.err:     org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:279)
System.err:     android.view.View.measure(View.java:18788)
System.err:     org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     org.nativescript.widgets.ContentLayout.onMeasure(ContentLayout.java:32)
System.err:     android.view.View.measure(View.java:18788)
System.err:     android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
System.err:     android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
System.err:     android.view.View.measure(View.java:18788)
System.err:     android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
System.err:     android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
System.err:     android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
System.err:     android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
System.err:     android.view.View.measure(View.java:18788)
System.err:     android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
System.err:     android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
System.err:     com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
System.err:     android.view.View.measure(View.java:18788)
System.err:     android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
System.err:     android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
System.err:     android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
System.err:     android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
System.err:     android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
System.err:     android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
System.err:     android.view.Choreographer.doCallbacks(Choreographer.java:670)
System.err:     android.view.Choreographer.doFrame(Choreographer.java:606)
System.err:     android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
System.err:     android.os.Handler.handleCallback(Handler.java:739)
System.err:     android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     android.os.Looper.loop(Looper.java:148)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5417)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
System.err: File: "file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js, line: 15104, column: 8
System.err: StackTrace:
System.err:     Frame: function:'getViewClass', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/nativescript-angular/element-registry.js', line: 88, column: 15
System.err:     Frame: function:'ViewUtil.createView', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/nativescript-angular/view-util.js', line: 201, column: 44
System.err:     Frame: function:'NativeScriptRenderer.createElement', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/nativescript-angular/renderer.js', line: 109, column: 30
System.err:     Frame: function:'DebugRenderer2.createElement', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 15203, column: 49
System.err:     Frame: function:'createElement', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 10576, column: 27
System.err:     Frame: function:'createViewNodes', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 13741, column: 61
System.err:     Frame: function:'createEmbeddedView', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 13657, column: 5
System.err:     Frame: function:'callWithDebugContext', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 15094, column: 42
System.err:     Frame: function:'debugCreateEmbeddedView', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 14406, column: 12
System.err:     Frame: function:'TemplateRef_.createEmbeddedView', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 11732, column: 38
System.err:     Frame: function:'ViewContainerRef_.createEmbeddedView', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 11444, column: 52
System.err:     Frame: function:'ListViewComponent.onItemLoading', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/nativescript-angular/directives/list-view-comp.js', line: 113, column: 35
System.err:     Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 100, column: 32
System.err:     Frame: function:'ListViewAdapter.getView', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/tns-core-modules/ui/list-view/list-view.js', line: 242, column: 24
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     at com.tns.gen.android.widget.BaseAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.getView(BaseAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.java:47)
System.err:     at android.widget.AbsListView.obtainView(AbsListView.java:2346)
System.err:     at android.widget.ListView.measureHeightOfChildren(ListView.java:1280)
System.err:     at android.widget.ListView.onMeasure(ListView.java:1188)
System.err:     at android.view.View.measure(View.java:18788)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.StackLayout.onMeasure(StackLayout.java:83)
System.err:     at android.view.View.measure(View.java:18788)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1055)
System.err:     at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:865)
System.err:     at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:279)
System.err:     at android.view.View.measure(View.java:18788)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.ContentLayout.onMeasure(ContentLayout.java:32)
System.err:     at android.view.View.measure(View.java:18788)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
System.err:     at android.view.View.measure(View.java:18788)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
System.err:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
System.err:     at android.view.View.measure(View.java:18788)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
System.err:     at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
System.err:     at android.view.View.measure(View.java:18788)
System.err:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
System.err:     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:606)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
System.err:     at android.os.Handler.handleCallback(Handler.java:739)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:148)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
ActivityManager: Process org.nativescript.demong (pid 3456) has died
17:28:08 - Compilation complete. Watching for file changes.
```

**Comment by xlmnxp** [comment]
remove platfrom folder and rebuild your project
